/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../studio/schema.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type VideoHero = {
  _type: "videoHero";
  heading: string;
  description: string;
  usps?: Array<string>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  image: CustomImage;
  video: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type TeamMember = {
  _type: "teamMember";
  name: string;
  jobTitle: string;
  jobDescription?: string;
  image: CustomImage;
};

export type Team = {
  _type: "team";
  heading: string;
  description: string;
  members?: Array<
    {
      _key: string;
    } & TeamMember
  >;
};

export type Services = {
  _type: "services";
  heading: string;
  description: string;
  logos?: Array<
    {
      _key: string;
    } & Logo
  >;
  costIndicationLink: RestrictedLink;
};

export type RestrictedLink = {
  _type: "restrictedLink";
  linkText: string;
  href: string;
};

export type Logo = {
  _type: "logo";
  href?: string;
  image: CustomImage;
};

export type Link = {
  _type: "link";
  linkText: string;
  href: string;
  openInNewTab?: boolean;
  isExternalLink?: boolean;
};

export type Hero = {
  _type: "hero";
  heading: string;
  description: string;
  usps?: Array<string>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  image: CustomImage;
};

export type EnrollForm = {
  _type: "enrollForm";
  heading: string;
  description: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CustomImage = {
  _type: "customImage";
  alt: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ContactDetail = {
  _type: "contactDetail";
  linkText: string;
  href: string;
  type: "email" | "phone" | "website" | "location";
};

export type Contact = {
  _type: "contact";
  heading: string;
  description: string;
  contactDetails?: Array<
    {
      _key: string;
    } & ContactDetail
  >;
};

export type AccordionItem = {
  _type: "accordionItem";
  heading: string;
  description: string;
};

export type Accordion = {
  _type: "accordion";
  heading: string;
  accordionItems?: Array<
    {
      _key: string;
    } & AccordionItem
  >;
};

export type EnrollPage = {
  _id: string;
  _type: "enrollPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  showEnrollmentPage?: boolean;
  enrollmentUnavailableText?: string;
  hero: Hero;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  hero: VideoHero;
  team: Team;
  services: Services;
  treatments: Accordion;
  image: CustomImage;
  faq: Accordion;
  contact: Contact;
  emergencyService: Contact;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Notification = {
  _id: string;
  _type: "notification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  description: string;
  showNotification?: boolean;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | VideoHero
  | TeamMember
  | Team
  | Services
  | RestrictedLink
  | Logo
  | Link
  | Hero
  | EnrollForm
  | SanityImageAssetReference
  | CustomImage
  | ContactDetail
  | Contact
  | AccordionItem
  | Accordion
  | EnrollPage
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | Notification
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == 'settings'][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: getHeaderPhoneQuery
// Query: *[_type == 'homePage'][0]{    "phone": contact.contactDetails[type == 'phone'][0]{linkText, href},  }
export type GetHeaderPhoneQueryResult = {
  phone: {
    linkText: string;
    href: string;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: getHomepageQuery
// Query: *[_type == 'homePage'][0]{    _id,    _type,    name,    hero{      ...,      video{asset->{url}},    },    faq,    services,    contact,    image,    emergencyService,    team,    treatments,  }
export type GetHomepageQueryResult = {
  _id: string;
  _type: "homePage";
  name: string;
  hero: {
    _type: "videoHero";
    heading: string;
    description: string;
    usps?: Array<string>;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    image: CustomImage;
    video: {
      asset: {
        url: string;
      } | null;
    };
  };
  faq: Accordion;
  services: Services;
  contact: Contact;
  image: CustomImage;
  emergencyService: Contact;
  team: Team;
  treatments: Accordion;
} | null;

// Source: sanity/lib/queries.ts
// Variable: getEnrollmentPageQuery
// Query: *[_type == 'enrollPage'][0]{    _id,    _type,    name,    showEnrollmentPage,    enrollmentUnavailableText,    hero,  }
export type GetEnrollmentPageQueryResult = {
  _id: string;
  _type: "enrollPage";
  name: string;
  showEnrollmentPage: boolean | null;
  enrollmentUnavailableText: string | null;
  hero: Hero;
} | null;

// Source: sanity/lib/queries.ts
// Variable: getNotificationQuery
// Query: *[_type == 'notification'][0]{    _id,    _type,    heading,    description,    showNotification,  }
export type GetNotificationQueryResult = {
  _id: string;
  _type: "notification";
  heading: string;
  description: string;
  showNotification: boolean | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<never>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'settings'][0]": SettingsQueryResult;
    "\n  *[_type == 'homePage'][0]{\n    \"phone\": contact.contactDetails[type == 'phone'][0]{linkText, href},\n  }\n": GetHeaderPhoneQueryResult;
    "\n  *[_type == 'homePage'][0]{\n    _id,\n    _type,\n    name,\n    hero{\n      ...,\n      video{asset->{url}},\n    },\n    faq,\n    services,\n    contact,\n    image,\n    emergencyService,\n    team,\n    treatments,\n  }\n": GetHomepageQueryResult;
    "\n  *[_type == 'enrollPage'][0]{\n    _id,\n    _type,\n    name,\n    showEnrollmentPage,\n    enrollmentUnavailableText,\n    hero,\n  }\n": GetEnrollmentPageQueryResult;
    "\n  *[_type == 'notification'][0]{\n    _id,\n    _type,\n    heading,\n    description,\n    showNotification,\n  }\n": GetNotificationQueryResult;
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult;
  }
}
