import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/features/Header/Header";
import { Footer } from "@/features/Footer/Footer";
import { NotificationModal } from "@/features/NotificationModal/NotificationModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main>
          <NotificationModal
            title="Let op: Gewijzigde openingstijd vandaag"
            description="Onze praktijk sluit vandaag een uur eerder dan gebruikelijk, namelijk om 16:00 uur.  Bedankt voor uw begrip!"
          />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
