import { defineQuery } from "next-sanity";

export const settingsQuery = defineQuery(`*[_type == 'settings'][0]`);

// const linkReference = /* groq */ `
//   _type == "link" => {
//     "page": page->slug.current,
//   }
// `;

// const linkFields = /* groq */ `
//   link {
//       ...,
//       ${linkReference}
//       }
// `;

export const getHomepageQuery = defineQuery(`
  *[_type == 'homePage'][0]{
    _id,
    _type,
    name,
    hero,
    faq,
    services,
    contact,
    image,
    emergencyService,
    team,
    treatments,
  }
`);

export const getEnrollmentPageQuery = defineQuery(`
  *[_type == 'enrollPage'][0]{
    _id,
    _type,
    name,
    showEnrollmentPage,
    enrollmentUnavailableText,
    hero,
  }
`);

export const getNotificationQuery = defineQuery(`
  *[_type == 'notification'][0]{
    _id,
    _type,
    heading,
    description,
    showNotification,
  }
`);

// TODO: refactor the sitemap implementation to fit our needs.
// Below was auto generated by the sanity.io setup.
export const sitemapData = defineQuery(`
  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {
    "slug": slug.current,
    _type,
    _updatedAt,
  }
`);
